name: Generate ASCII Artwork
on: [push]
jobs:
    asciijob:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v5
            - name: Executing Shell script with Permission
              run: |
                chmod +x .github/workflows/ascii-script.sh
                .github/workflows/ascii-script.sh