name: Matrix Configuration

on:
  push:
  workflow_dispatch:

jobs:
  deploy-on:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, windows-latest]
        images: [hello-world, alpine, busybox]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Echo Docker Details
      run: docker info
    
    - name: Run Images on ${{ matrix.os }}
      run: docker run ${{ matrix.images }}

 
