name: Exploring Variables and Secrets

#on: push
on:
  workflow_dispatch:
  #schedule:
  # - cron: '*/1 * * * *'
env:
  CONTAINER_REGISTRY: docker.io
# DOCKER_USERNAME: lukmanadeokun31
  IMAGE_NAME: github-actions-nginx
# DOCKER_PASSWORD: s3cUrePassw0rd

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Build
      run: docker build -t $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/IMAGE_NAME:latest
    
    - name: Docker Login
      run: docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

    - name: Docker publish
      run: docker push $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
    - name: Docker run
      run: docker run -d -p 8080:80 $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

